site_name: Car API Documentation
site_description: Uma API REST completa para gerenciamento de carros.
site_author: L.Phillipe

theme:
  name: material
  font:
    text: Roboto

plugins:
  - search

nav:
  - Início: index.md
  - Visão geral: overview.md
  - Pré-requisitos: prerequisites.md
  - Instalação: installation.md
  - Configuração: configuration.md
  - Guidelines e padrões: guidelines.md
  - Estrutura: structure.md
  - API Endpoints: api-endpoints.md
  - Modelagem do Sistema: system-modeling.md
  - Autenticação e segurança: authentication.md
  - Desenvolvimento: development.md
  - Testes: testing.md
  - Deploy: deployment.md
  - Contribuição: contributing.md
  - Release Notes: release-notes.md


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
